version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:6.10
      - image: localstack/localstack
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn/
          key: v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Run test
          command: |
            yarn test

